apiVersion: skaffold/v4beta6
kind: Config
build:
  # googleCloudBuild:
  #   logging: CLOUD_LOGGING_ONLY
  # tagPolicy:
  #   inputDigest: {}
  artifacts:
    - image: jitendrapalei/gateway:latest
      context: ../..
      docker:
        dockerfile: apps/gateway/Dockerfile
    - image: jitendrapalei/control-plane-service:latest
      context: ../..
      docker:
        dockerfile: apps/control-plane/Dockerfile
    - image: jitendrapalei/event-collector-service:latest
      context: ../..
      docker:
        dockerfile: apps/event-collector/Dockerfile
    - image: jitendrapalei/worker:latest
      context: ../..
      docker:
        dockerfile: apps/worker/Dockerfile
deploy:
  helm:
    releases:
      - name: honojs-apis
        chartPath: helm/honojs-api
        valuesFiles:
          - helm/honojs-api/values.yaml

profiles:
  - name: dev
    deploy:
      helm:
        releases:
          - name: honojs-apis
            chartPath: helm/honojs-api
            namespace: dev
  - name: prod
    deploy:
      helm:
        releases:
          - name: honojs-apis
            chartPath: helm/honojs-api
            namespace: prod
